import type { Exercise } from "@/lib/workout-types";

export const EXERCISES: Exercise[] = [
  {
    id: "wall-push-up",
    name: "Wall push-up",
    type: "strength",
    level: "beginner",
    goals: ["muscle_gain", "general_fitness"],
    duration: 4,
    reps: 12,
    lowImpact: true,
    video: "/videos/chest/chest_ex5_wall_push_up.mp4",
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight squat",
    type: "strength",
    level: "beginner",
    goals: ["weight_loss", "muscle_gain", "general_fitness"],
    duration: 5,
    reps: 15,
    lowImpact: true,
    video: "/videos/leg/legs_ex1_bodyweight_squat.mp4",
  },
  {
    id: "glute-bridge",
    name: "Glute bridge",
    type: "strength",
    level: "beginner",
    goals: ["general_fitness", "muscle_gain"],
    duration: 4,
    reps: 15,
    lowImpact: true,
    video: "/videos/leg/legs_ex5_glute_bridge.mp4",
  },
  {
    id: "basic-crunch",
    name: "Basic crunch",
    type: "core",
    level: "beginner",
    goals: ["general_fitness", "muscle_gain"],
    duration: 4,
    reps: 20,
    lowImpact: true,
    video: "/videos/abs/ex1.mp4",
  },
  {
    id: "marching-in-place",
    name: "Marching in place",
    type: "cardio",
    level: "beginner",
    goals: ["weight_loss", "general_fitness"],
    duration: 5,
    reps: 40,
    lowImpact: true,
  },
  {
    id: "standing-calf-raise",
    name: "Standing calf raise",
    type: "strength",
    level: "beginner",
    goals: ["general_fitness", "muscle_gain"],
    duration: 3,
    reps: 20,
    lowImpact: true,
  },
  {
    id: "arm-circles",
    name: "Arm circles",
    type: "mobility",
    level: "beginner",
    goals: ["general_fitness", "flexibility"],
    duration: 3,
    reps: 20,
    lowImpact: true,
  },
  {
    id: "standard-push-up",
    name: "Standard push-up",
    type: "strength",
    level: "intermediate",
    goals: ["muscle_gain", "general_fitness"],
    duration: 5,
    reps: 12,
    lowImpact: true,
    video: "/videos/chest/chest_ex1_standard_push_up.mp4",
  },
  {
    id: "forward-lunge",
    name: "Forward lunge",
    type: "strength",
    level: "intermediate",
    goals: ["weight_loss", "muscle_gain", "general_fitness"],
    duration: 5,
    reps: 12,
    lowImpact: true,
    video: "/videos/leg/legs_ex3_forward_lunge.mp4",
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle crunch",
    type: "core",
    level: "intermediate",
    goals: ["muscle_gain", "weight_loss"],
    duration: 4,
    reps: 20,
    lowImpact: true,
    video: "/videos/abs/ex3.mp4",
  },
  {
    id: "jumping-jacks",
    name: "Jumping jacks",
    type: "cardio",
    level: "intermediate",
    goals: ["weight_loss", "general_fitness"],
    duration: 4,
    reps: 30,
    lowImpact: false,
  },
  {
    id: "dumbbell-row",
    name: "Bent-over row",
    type: "strength",
    level: "intermediate",
    goals: ["muscle_gain", "general_fitness"],
    duration: 6,
    reps: 10,
    lowImpact: true,
    video: "/videos/back/back_ex3_bent_over_row.mp4",
  },
  {
    id: "high-knees",
    name: "High knees",
    type: "cardio",
    level: "intermediate",
    goals: ["weight_loss", "general_fitness"],
    duration: 4,
    reps: 30,
    lowImpact: false,
  },
  {
    id: "plank",
    name: "Forearm plank",
    type: "core",
    level: "intermediate",
    goals: ["muscle_gain", "general_fitness"],
    duration: 4,
    lowImpact: true,
    video: "/videos/abs/ex7.mp4",
  },
  {
    id: "explosive-push-up",
    name: "Explosive push-up",
    type: "strength",
    level: "expert",
    goals: ["muscle_gain", "general_fitness"],
    duration: 5,
    reps: 8,
    lowImpact: false,
    video: "/videos/chest/chest_ex3_explosive_push_up.mp4",
  },
  {
    id: "jump-squat",
    name: "Jump squat",
    type: "strength",
    level: "expert",
    goals: ["weight_loss", "muscle_gain", "general_fitness"],
    duration: 5,
    reps: 12,
    lowImpact: false,
    video: "/videos/leg/legs_ex4_jump_squat.mp4",
  },
  {
    id: "pull-up",
    name: "Pull-up",
    type: "strength",
    level: "expert",
    goals: ["muscle_gain", "general_fitness"],
    duration: 6,
    reps: 8,
    lowImpact: true,
    video: "/videos/back/back_ex4_pull_up.mp4",
  },
  {
    id: "burpee",
    name: "Burpee",
    type: "cardio",
    level: "expert",
    goals: ["weight_loss", "general_fitness"],
    duration: 5,
    reps: 10,
    lowImpact: false,
  },
  {
    id: "v-sit-hold",
    name: "V-sit hold",
    type: "core",
    level: "expert",
    goals: ["muscle_gain", "general_fitness"],
    duration: 4,
    lowImpact: true,
    video: "/videos/abs/ex6.mp4",
  },
  {
    id: "dynamic-stretch-flow",
    name: "Dynamic stretch flow",
    type: "flexibility",
    level: "beginner",
    goals: ["flexibility", "general_fitness"],
    duration: 6,
    lowImpact: true,
  },
];
